// This file is part of IFStile project
// Copyright (C)2026 Dmitry Mekhontsev <mekhontsev@gmail.com>

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// at your option any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#pragma once


//the order corresponds to descending priority
enum class ETYPE : uint8_t
{
	//not defined (maximum priority)
	undef = 0,//results from clear()

	//$
	this_vector,

	//empty
	empty,

	//identity
	id,

	//pi constant
	pi,

	//small nunber (in header)	
	number_imm,

	//number
	number,

	//inverse: 1/arg
	inv,

	//-arg
	neg,

	//vector of numbers
	vector_imm,

	//$(...)
	vector_func,

	//$union
	vector_union,

	//vector of operators
	vector,

	//left - means indexing a variable, for example a[0, 3] = ...
	var_index = vector,

	//companion matrix, arguments are vectors (normalized polynomials)
	//if there are no arguments, the identity matrix
	companion,

	//diagonal matrix
	diagonal,

	//exchange matrix
	exchange,

	//reflection relative to the unit ball
	inversion,

	//characteristic polynomial
	charpoly,

	//reference to another operator (header only)
	reference,

	//reference to a string identifier, not replaced by the linker
	unk_reference,

	//built-in function
	call_built_in,

	////////////////////////////////////////////////////////////////////////////
	//block_ref + list of arguments
	call,

	////////////////////////////////////////////////////////////////////////////
	//a number from an interval
	//stores the distribution index in the graph
	set_interval,

	template_first = set_interval,

	//semigroup generated by the components of the argument vector
	//stores the index of the semigroup + distribution in the graph
	set_semigroup,//DEPRECATED

	//set of vectors with components equal to empty or identity maps
	//stores the distribution index in the graph
	set_binary,//DEPRECATED

	//set of vectors with integer or real components
	//stores the distribution index in the graph
	set_vector,

	//set of permutations of a multiset
	set_permutation,

	template_last = set_permutation,
	////////////////////////////////////////////////////////////////////////////

	//distribution and type for set operators (integer)
	distribution_int,

	//distribution and type for set operators (real)
	distribution_real,

	//color (geometrically identity)
	color_style,

	thickness,


	//if(
	//	cond_0, val_0
	//	cond_1, val_1
	//	cond_2, val_2,
	//	val_else
	//)
	condition,//odd number of arguments

	////////////////////////////////////////////////////////////////////////////

	//the specified vector element
	//argument - what to index (vector, element, or reference)
	//index - in the header (u24)
	index_imm,

	//the specified vector element
	//the first argument is what we're indexing (vector, element, or reference)
	//the second argument is the index
	index,

	//degree (first argument is the base, exponent is in the header)
	power_imm,

	//degree (the first argument is the base, the second is the exponent)
	power,

	//modulus: a%b
	mod,

	//composition and multiplication
	mul,

	//sum (for numbers, vectors of the same length and affine)
	sum,

	//union
	uni,

	csg, //$csg(map: other, with: int, power: int, inv_all_maps: int)


	//minimum priority

	num_elems,
	min_priority = num_elems,
};

static_assert((uint8_t)ETYPE::min_priority <= 64);


//only 2 bits can be used for subtype
enum class ESUBTYPE : uint8_t
{
	zero = 0,

	//for number, number_imm, vector_imm
	integer = 0, //64-bit integer
	rational = 1, //rational - numerator and denominator are 32 bits each
	real = 2, //64-bit real
	big = 3, //large number

	//for distribution
	dist_normal_def = 0,
	dist_normal		= 1,
	dist_uniform	= 2,

	//for call
	call_normal = 0,
	call_fields = 1,
	call_new = 2,

	//for references
	ref_graph = 0,
	ref_js = 1,
	ref_unknown = 2,//linker processing required

	//for left vector
	vector_normal = 0,
	vector_sub = 1,
};


//The operator consists of a header and arguments
//some of the data is stored in the header
//the rest is stored separately at a known offset
struct ims_operator
{
	//8 bits: type+subtype
	ETYPE tt : 6;
	ESUBTYPE ts : 2;

	//24-bit:
	//for power_imm - the exponent, index_imm - the index
	//for the rest - the number of arguments
	uint8_t	 u24[3];

	//32 bits:
	//for number_imm - the direct int32_t value
	//for a reference - the index of the named operator in the inheritance hierarchy
	//for the rest - the beginning of the argument list
	union {
		uint32_t u32;
		int32_t  i32;
		int16_t	 r16[2];
		float	 f32;
	};

	////////////////////////////////////////////////////////////////////////////

	size_t get_u24() const;
	void set_u24(size_t v);

	intptr_t get_i24() const;
	bool set_i24(intptr_t v);
	
	void set_i32(intptr_t v);
	void set_u32(size_t v);

	//empty set
	bool is_xempty() const;
	//set empty union
	void set_xempty();

	void set_xundef();
	bool is_xundef() const;

	//identity operator
	bool is_id() const;
	//set an empty composition
	void set_id();

	void clear();

	void set_color();

	void set_thickness();
	
	uint64_t as64() const;

	
	
	//guaranteed to be closed (for example, a ball)
	bool is_closed() const;

	bool is_template() const;

	intptr_t get_pow_exponent_imm() const;
	intptr_t get_elem_index() const;

	size_t get_builtin_func() const { return get_u24(); };
	size_t get_builtin_args() const;
	void set_builtin_func(size_t id) { set_u24(id); };

	
	//number of operator arguments
	size_t num_args() const { return get_u24(); };
	size_t get_offset() const { return u32; };
	block_id_t get_unk_id() const { return u32; };
	void set_offset(size_t offset);

	//set a number from a small range
	void set_small_int(int32_t v);
	void set_small_rational(int16_t n, int16_t d);

	bool is_distirib_def() const;

	void set_reference(size_t offset, ESUBTYPE ts_ = ESUBTYPE::ref_graph);
	void set(ETYPE t, size_t primary, size_t secondary);
	
	bool get_int_imm(int64_t& numerator, int64_t& denominator) const;

	static ETYPE from_string(std::string_view str);
	static std::string_view to_string(ETYPE t);

	static consteval auto get_topo_eval_arr()
	{
		//types that require non-trivial operator evaluation
		//all others are immediately wrapped in ast_ptr
		std::array<bool, (size_t)ETYPE::num_elems> ret{ false };
		auto set = [&](ETYPE t) {ret[(size_t)t] = true; };
		set(ETYPE::empty);	//turn into an empty union
		set(ETYPE::id);		//convert to an empty composition
		set(ETYPE::call);			//the function itself is calculated geometrically
		set(ETYPE::condition);		//conditions are calculated geometrically
		set(ETYPE::power_imm);
		set(ETYPE::power);			//the exponent is calculated geometrically
		set(ETYPE::index_imm);
		set(ETYPE::index);			//indices are calculated geometrically
		set(ETYPE::reference);
		set(ETYPE::vector_union);
		set(ETYPE::uni);
		set(ETYPE::mul);
		return ret;
	};

	static bool is_topo_eval(ETYPE t)
	{
		static constexpr auto is_topo_eval_arr{ get_topo_eval_arr() };
		static_assert(is_topo_eval_arr[(size_t)ETYPE::mul] == true);
		static_assert(is_topo_eval_arr[(size_t)ETYPE::sum] == false);
		return is_topo_eval_arr[(size_t)t];
	}

	//number of arguments - not operators
	size_t data_args() const;

	//number of operator arguments (i.e. those with their own ims_operator header)
	size_t oper_args() const;

	//for hashing when constructing a graph
	void hash_combine(size_t& ret) const;

	//for sorting
	static intptr_t lexic_compare(ims_operator h1, ims_operator h2);
	static bool is_i24(intptr_t v);
};

static_assert(sizeof(ims_operator) == sizeof(int64_t), "invalid size");


enum class builtin_ids : size_t
{
	subspace,
	root,
	section,
	camera,
	palette,
	background,
	colorize,
	light,
	num_ids,
};



using var_header_type = uint32_t;

constexpr size_t c_num_builtins = (size_t)builtin_ids::num_ids;
//We use uint32_t because the reference must fit
//ims_operator::u32 and var_header::ref4
//anything >=var_header::nil is an invalid reference
constexpr size_t c_graph_max_ref =
std::numeric_limits<var_header_type>::max() - c_num_builtins;

constexpr builtin_ids ref2builtin(size_t ref)
{
	return static_cast<builtin_ids>(ref - c_graph_max_ref);
}

constexpr bool ref_is_builtin(size_t ref)
{
	return ref >= c_graph_max_ref;
}

constexpr bool ref_is_builtin(size_t ref, builtin_ids bid)
{
	return ref_is_builtin(ref) && ref2builtin(ref) == bid;
}

constexpr size_t builtin2ref(builtin_ids bid)
{
	return  c_graph_max_ref + static_cast<size_t>(bid);
}


builtin_ids get_builtin_id(std::string_view name);
std::string_view  get_builtin_name(builtin_ids id);

///////////////////////////////////////////////////////////////
//within the AST, immediately after var_header, there are two blocks
//left side of the assignment
//right side (variable definition)
struct var_header
{
	using type = var_header_type;

	//has a different meaning at the block loading stage
	//the low-order bit means subs
	type ref8; //index in m_refs
	type next; //offset of the next variable

	static constexpr type pack(size_t ref, bool is_subs) 
	{
		if (ref_is_builtin(ref)) {
			return (type)ref;
		}
		return type((ref << 1) | (is_subs ? 1 : 0));
	}

	static constexpr size_t unpack_ref(type ref)
	{
		return ref >> 1;
	}

	static constexpr bool unpack_subs(type ref)
	{
		return (ref & 1) != 0;
	}

	size_t get_ref() const 
	{
		return unpack_ref(ref8);
	}

	bool is_subs() const
	{
		return unpack_subs(ref8);
	}

	bool is_builtin() const
	{
		return ref_is_builtin(ref8);
	}

	bool is_builtin(builtin_ids bid) const
	{
		return ref_is_builtin(ref8, bid);
	}

	//next == nil : there is no next var
	static constexpr type nil = std::numeric_limits<type>::max();

	static constexpr type offset_left = 1;
	static constexpr type offset_right = 2;
	//how many elements does the variable declaration take?
	//var_header + left expression + right expression
	static constexpr type total_elems = 3;
};

///////////////////////////////////////////////////////////////
union sval
{
	ims_operator hdr;
	var_header vh;
	double	f64;
	int64_t i64;
	uint64_t u64;
	int32_t rt[2];//rational
	//void* ptrdata;//pointer to a large number
};

static_assert(sizeof(sval) == sizeof(int64_t), "invalid size");

