// This file is part of IFStile project
// Copyright (C)2026 Dmitry Mekhontsev <mekhontsev@gmail.com>

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// at your option any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#pragma once
#include "dyn_mat_vec.h"

//a matrix group generated by several generators
//if the subgroup generated by finite-order elements is finite, then
//fill in information about it (multiplication table, etc.)
struct matrix_group
{
	using Integer = int64_t;
	using Matrix = DynMat<Integer>;

	//maximum number of elements in a group
	static const size_t s_max_group = 3840;

	struct gen_info
	{
		//sequence number
		size_t idx;

		//the degree at which an element becomes an identity matrix
		size_t deg;

		//generator's matrix
		Matrix m;
	};



	struct factor
	{
		factor(size_t i, size_t p);
		using type = uint8_t;
		type idx;
		type pw;

		static const type max_degree = 100;
	};

	//element of the finite group
	struct elem_info
	{
		//sequence number in a group of the same weight
		size_t idx;
		
		//sum of the exponents of the factors
		//elements of finite order to any power have weight=1
		size_t weight;

		//decomposition of an element into generators
		boost::container::small_vector<factor, 10> factors;
	};

	
	struct matrix_hash
	{
		size_t operator()(const Matrix& e) const;
	};


	using Hash = UNAMESPACE::unordered_map<Matrix, elem_info, matrix_hash>;

	using elem_ref = typename Hash::value_type*;

	////////////////////////////////////////////////////////////////////////////

	//all generators
	std::vector<gen_info> m_gens;
	
	//all elements of the group in the order they are found
	std::vector<elem_ref> m_elems;

	//groups of one weight, starting with weight 1
	std::vector<std::vector<elem_ref>> m_weights;
	////////////////////////////////////////////////////////////////////////////

	void clear();

	//add generator to group, converts it to normal form
	void add_generator(const Matrix& m);

	void sort_gens();


	void init();

	const elem_info* find(const Matrix& m) const;

	//the group's finiteness has already been determined
	bool finite() const;
	
	//performs one iteration of group expansion using products
	//returns false if the group is closed and will not expand any further
	//if done from multiple threads, protection (mutex) is required
	bool extend();
private:

	

	//for quick search of matrices
	Hash m_hash;

	bool m_overflow;

	//what part of the multiplication table has already been processed
	size_t m_i = 0;
	size_t m_j = 0;
	size_t m_k = 0;

	//for temporary needs
	Matrix m_temp, m_tempM;
	elem_info H;

};

